### ISSUE TITLE
[BUG] runway does not work with cfn-lint>=0.29.4

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#262]
This version introduced a new positional argument resulting in the following error.

```
INFO:runway:======= Running test 'cfn-lint' ===========================
Traceback (most recent call last):
  File "/Users/person/.pyenv/versions/3.8.2/lib/python3.8/site-packages/runway/commands/runway/test.py", line 71, in execute
    handler.handle(test.name, test.args)
  File "/Users/person/.pyenv/versions/3.8.2/lib/python3.8/site-packages/runway/tests/handlers/cfn_lint.py", line 73, in handle
    exit_code = cls.run_cfnlint(args.get('cli_args', ''))
  File "/Users/person/.pyenv/versions/3.8.2/lib/python3.8/site-packages/runway/tests/handlers/cfn_lint.py", line 44, in run_cfnlint
    cfnlint.core.run_cli(  # pylint: disable=no-value-for-parameter
TypeError: run_cli() missing 1 required positional argument: 'build_graph'
ERROR:runway:Test failed: cfn-lint
```

will likely need to add a requirement of `cfn-lint>=0.29.4` to runway.

The positional arg was added to **line 25** of `src/cfnlint/__main__,py` in [v0.29.4](https://github.com/aws-cloudformation/cfn-python-lint/compare/v0.29.3...v0.29.4#diff-c74a0d68d2f6968f6e85626a79bc48a6R25).
